apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: 'common01-deployer'
spec:
  project: default
  source:
    repoURL: 'https://code.europa.eu/api/v4/projects/951/packages/helm/stable'
    path: '""'
    targetRevision: 2.4.1
    helm:
      values: |
        values:
          branch: v2.4.1
        resourcePreset: low
        agentList:
          authorities:
            - authority01
          consumers:
            - consumer01
          providers:
            - dataprovider01
        project: default
        namespaceTag: common01
        domainSuffix: ds.helsinki.tfds.io
        argocd:
          appname: common01
          namespace: argocd
        cluster:
          address: https://kubernetes.default.svc
          namespace: common01
          issuer: dev-prod
          internalIssuer: self-signed-issuer
          kubeStateHost: kube-prometheus-stack-kube-state-metrics.devsecopstools.svc.cluster.local:8080
        secrets:
          secretEngine: example
          role: example-role
        kafka:
          ha: false
          topic:
            autocreate: true
        mailpit:
          enabled: true
        monitoring:
          enabled: true
    chart: common_components
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: common01